import './movieCard.js';
import './movieList.js';
import './countdownLive.js';
import './seatSelector.js';
import './Header.js';
import './Footer.js';
import './Quickbook.js';
import './main slider/slider-element.js';
import './main slider/Slider.js';
import './Filter.js';